import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Tajawal', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Tajawal', 'Geist', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      colors: {
        'surface-page': 'var(--surface-page)',
        'surface-canvas': 'var(--surface-canvas)',
        'surface-card': 'var(--surface-card)',
        'surface-raised': 'var(--surface-raised)',
        'surface-subtle': 'var(--surface-subtle)',
        'surface-inset': 'var(--surface-inset)',
        'surface-input': 'var(--surface-input)',
        'surface-overlay': 'var(--surface-overlay)',

        'fg-primary': 'var(--fg-primary)',
        'fg-secondary': 'var(--fg-secondary)',
        'fg-muted': 'var(--fg-muted)',
        'fg-on-accent': 'var(--fg-on-accent)',
        'fg-success': 'var(--fg-success)',
        'fg-warning': 'var(--fg-warning)',
        'fg-danger': 'var(--fg-danger)',
        'fg-info': 'var(--fg-info)',

        'border-subtle': 'var(--border-subtle)',
        'border-default': 'var(--border-default)',
        'border-strong': 'var(--border-strong)',
        'border-focus': 'var(--border-focus)',

        'accent': 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-subtle': 'var(--accent-subtle)',
        'accent-foreground': 'var(--accent-foreground)',

        'status-success': 'var(--status-success)',
        'status-success-subtle': 'var(--status-success-subtle)',
        'status-warning': 'var(--status-warning)',
        'status-warning-subtle': 'var(--status-warning-subtle)',
        'status-danger': 'var(--status-danger)',
        'status-danger-subtle': 'var(--status-danger-subtle)',
        'status-info': 'var(--status-info)',
        'status-info-subtle': 'var(--status-info-subtle)',
      },
      borderRadius: {
        'shape-xs': '4px',
        'shape-sm': '8px',
        'shape-md': '12px',
        'shape-lg': '16px',
        'shape-full': '9999px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '16px',
        '2xl': '16px',
        full: '9999px',
      },
      fontSize: {
        // Material 3 Type Scale
        'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px', fontWeight: '700' }],
        'display-md': ['45px', { lineHeight: '52px', letterSpacing: '0px', fontWeight: '700' }],
        'display-sm': ['36px', { lineHeight: '44px', letterSpacing: '0px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0px', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '0px', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '32px', letterSpacing: '0px', fontWeight: '600' }],
        'title-lg': ['22px', { lineHeight: '28px', letterSpacing: '0px', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0.15px', fontWeight: '600' }],
        'title-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.25px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.4px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '600' }],
      },
      boxShadow: {
        'elevation-0': 'var(--sys-elevation-0)',
        'elevation-1': 'var(--sys-elevation-1)',
        'elevation-2': 'var(--sys-elevation-2)',
        'elevation-3': 'var(--sys-elevation-3)',
        'elevation-4': 'var(--sys-elevation-4)',
        'elevation-5': 'var(--sys-elevation-5)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      transitionDuration: {
        fast: 'var(--motion-fast)',
        base: 'var(--motion-base)',
        slow: 'var(--motion-slow)',
      },
      transitionTimingFunction: {
        ease: 'var(--motion-ease)',
      },
      minHeight: {
        'screen-safe': '100dvh',
      },
      height: {
        'screen-safe': '100dvh',
      },
    },
  },
  plugins: [],
} satisfies Config;
