import { ThemeTokensMap } from '../types';

export const DEFAULT_LIGHT_TOKENS: ThemeTokensMap = {
  '--surface-page': '#ffffff',
  '--surface-canvas': '#ffffff',
  '--surface-card': '#ffffff',
  '--surface-raised': '#ffffff',
  '--surface-subtle': '#f6f8fa',
  '--surface-inset': '#f6f8fa',
  '--surface-sidebar': '#ffffff',
  '--surface-code': '#161b22',
  '--surface-overlay': 'rgba(31, 35, 40, 0.4)',

  '--fg-primary': '#1f2328',
  '--fg-secondary': '#32383f',
  '--fg-muted': '#656d76',
  '--fg-disabled': '#afb8c1',
  '--fg-on-emphasis': '#ffffff',
  '--font-display': '"Cairo", "Geist", system-ui, sans-serif',
  '--font-sans': '"Cairo", "Geist", system-ui, -apple-system, sans-serif',
  '--font-mono': '"Geist Mono", "JetBrains Mono", monospace',

  '--accent': '#0969da',
  '--accent-hover': '#0550ae',
  '--fg-accent': '#0969da',
  '--bg-accent-emphasis': '#1a7f37',
  '--bg-accent-muted': 'rgba(9, 105, 218, 0.12)',
  '--border-accent-emphasis': '#0969da',
  '--focus-outline': '#0969da',

  '--border-default': '#d0d7de',
  '--border-outer-input': '#d0d7de',
  '--border-inner-input': '#d0d7de',
  '--border-subtle': 'rgba(208, 215, 222, 0.8)',
  '--border-strong': '#656d76',
  '--border-accent': '#0969da',

  '--bg-btn-primary': '#1a7f37',
  '--fg-btn-primary': '#ffffff',
  '--bg-btn-secondary': '#f6f8fa',
  '--border-btn-secondary': '#d0d7de',
  '--fg-btn-secondary': '#1f2328',
  '--bg-btn-danger': '#cf222e',
  '--fg-btn-danger': '#ffffff',
  '--bg-btn-success': '#1a7f37',
  '--fg-btn-success': '#ffffff',
  '--bg-btn-page': '#f6f8fa',
  '--fg-btn-page': '#1f2328',
  '--border-btn-page': '#d0d7de',
  '--bg-followup-btn': 'transparent',
  '--fg-followup-btn': '#656d76',
  '--border-followup-btn': 'transparent',
  '--bg-followup-btn-hover': '#ffffff',
  '--fg-followup-btn-hover': '#1f2328',
  '--border-followup-btn-hover': '#d0d7de',
  '--control-active-bg': '#1a7f37',
  '--control-active-fg': '#ffffff',

  '--btn-header-size': '32px',
  '--btn-header-radius': '8px',
  '--btn-header-border': '#d0d7de',
  '--btn-header-bg': 'transparent',
  '--btn-header-hover': '#f6f8fa',

  '--btn-input-size': '32px',
  '--btn-input-radius': '8px',
  '--btn-input-border': '#d0d7de',
  '--btn-input-bg': 'transparent',
  '--btn-input-hover': '#f6f8fa',

  '--btn-tool-size': '32px',
  '--btn-tool-radius': '8px',
  '--btn-tool-border': '#d0d7de',
  '--btn-tool-bg': 'transparent',
  '--btn-tool-hover': '#f6f8fa',

  '--btn-action-size': '32px',
  '--btn-action-radius': '8px',
  '--btn-action-border': '#d0d7de',
  '--btn-action-bg': 'transparent',
  '--btn-action-hover': '#f6f8fa',

  '--bg-input': '#ffffff',
  '--border-focus': '#0969da',

  '--admin-nav-bg': '#ffffff',
  '--admin-nav-item-active': '#f6f8fa',
  '--admin-header-bg': '#ffffff',
  '--admin-card-border': '#d0d7de',
  '--admin-table-header-bg': '#f6f8fa',
  '--admin-table-row-hover': '#f6f8fa',

  '--chat-bubble-user': '#f6f8fa',
  '--chat-bubble-assistant': 'transparent',
  '--chat-bubble-user-text': '#1f2328',
  '--chat-bubble-assistant-text': '#1f2328',

  '--fg-success': '#1a7f37',
  '--fg-warning': '#bc4c00',
  '--fg-danger': '#cf222e',
  '--fg-info': '#0969da',
  '--status-success-subtle': 'rgba(26, 127, 55, 0.12)',
  '--status-warning-subtle': 'rgba(188, 76, 0, 0.12)',
  '--status-danger-subtle': 'rgba(207, 34, 46, 0.10)',
  '--status-info-subtle': 'rgba(9, 105, 218, 0.12)',

  '--github-green': '#1a7f37',
  '--github-purple': '#8250df',
  '--github-blue': '#0969da',
  '--github-orange': '#bc4c00',
  '--github-pink': '#bf3989',

  '--radius-xs': '4px',
  '--radius-sm': '8px',
  '--radius-md': '12px',
  '--radius-lg': '16px',
  '--radius-xl': '16px',
  '--radius-full': '9999px',
  '--shadow-sm': '0 1px 3px 0 rgba(0, 0, 0, 0.08)',
  '--shadow-md': '0 2px 6px 0 color-mix(in oklab, var(--github-green) 30%, transparent)',
  '--shadow-lg': '0 12px 32px -8px rgba(0, 0, 0, 0.5), 0 4px 12px -2px rgba(0, 0, 0, 0.25)'
};

export const DEFAULT_DARK_TOKENS: ThemeTokensMap = {
  '--surface-page': '#0d1117',
  '--surface-canvas': '#0d1117',
  '--surface-card': '#161b22',
  '--surface-raised': '#161b22',
  '--surface-subtle': '#161b22',
  '--surface-inset': '#010409',
  '--surface-sidebar': '#0d1117',
  '--surface-code': '#010409',
  '--surface-overlay': 'rgba(1, 4, 9, 0.88)',

  '--fg-primary': '#e6edf3',
  '--fg-secondary': '#8b949e',
  '--fg-muted': '#8b949e',
  '--fg-disabled': '#484f58',
  '--fg-on-emphasis': '#ffffff',
  '--font-display': '"Cairo", "Geist", system-ui, sans-serif',
  '--font-sans': '"Cairo", "Geist", system-ui, -apple-system, sans-serif',
  '--font-mono': '"Geist Mono", "JetBrains Mono", monospace',

  '--accent': '#58a6ff',
  '--accent-hover': '#79c0ff',
  '--fg-accent': '#58a6ff',
  '--bg-accent-emphasis': '#238636',
  '--bg-accent-muted': 'rgba(88, 166, 255, 0.15)',
  '--border-accent-emphasis': '#58a6ff',
  '--focus-outline': '#58a6ff',

  '--border-default': '#3d444d',
  '--border-outer-input': '#3d444d',
  '--border-inner-input': '#3d444d',
  '--border-subtle': 'rgba(61, 68, 77, 0.6)',
  '--border-strong': '#8b949e',
  '--border-accent': '#58a6ff',

  '--bg-btn-primary': '#238636',
  '--fg-btn-primary': '#ffffff',
  '--bg-btn-secondary': '#161b22',
  '--border-btn-secondary': '#3d444d',
  '--fg-btn-secondary': '#e6edf3',
  '--bg-btn-danger': '#f85149',
  '--fg-btn-danger': '#ffffff',
  '--bg-btn-success': '#238636',
  '--fg-btn-success': '#ffffff',
  '--bg-btn-page': '#161b22',
  '--fg-btn-page': '#e6edf3',
  '--border-btn-page': '#3d444d',
  '--bg-followup-btn': 'transparent',
  '--fg-followup-btn': '#8b949e',
  '--border-followup-btn': 'transparent',
  '--bg-followup-btn-hover': '#161b22',
  '--fg-followup-btn-hover': '#e6edf3',
  '--border-followup-btn-hover': '#3d444d',
  '--control-active-bg': '#238636',
  '--control-active-fg': '#ffffff',

  '--btn-header-size': '32px',
  '--btn-header-radius': '8px',
  '--btn-header-border': '#3d444d',
  '--btn-header-bg': 'transparent',
  '--btn-header-hover': '#161b22',

  '--btn-input-size': '32px',
  '--btn-input-radius': '8px',
  '--btn-input-border': '#3d444d',
  '--btn-input-bg': 'transparent',
  '--btn-input-hover': '#161b22',

  '--btn-tool-size': '32px',
  '--btn-tool-radius': '8px',
  '--btn-tool-border': '#3d444d',
  '--btn-tool-bg': 'transparent',
  '--btn-tool-hover': '#161b22',

  '--btn-action-size': '32px',
  '--btn-action-radius': '8px',
  '--btn-action-border': '#3d444d',
  '--btn-action-bg': 'transparent',
  '--btn-action-hover': '#161b22',

  '--bg-input': '#21262d',
  '--border-focus': '#58a6ff',

  '--admin-nav-bg': '#0d1117',
  '--admin-nav-item-active': '#161b22',
  '--admin-header-bg': '#0d1117',
  '--admin-card-border': '#3d444d',
  '--admin-table-header-bg': '#161b22',
  '--admin-table-row-hover': '#161b22',

  '--chat-bubble-user': '#161b22',
  '--chat-bubble-assistant': 'transparent',
  '--chat-bubble-user-text': '#e6edf3',
  '--chat-bubble-assistant-text': '#e6edf3',

  '--fg-success': '#238636',
  '--fg-warning': '#db6d28',
  '--fg-danger': '#f85149',
  '--fg-info': '#58a6ff',
  '--status-success-subtle': 'rgba(35, 134, 54, 0.15)',
  '--status-warning-subtle': 'rgba(219, 109, 40, 0.12)',
  '--status-danger-subtle': 'rgba(248, 81, 73, 0.15)',
  '--status-info-subtle': 'rgba(88, 166, 255, 0.15)',

  '--github-green': '#238636',
  '--github-purple': '#a371f7',
  '--github-blue': '#58a6ff',
  '--github-orange': '#db6d28',
  '--github-pink': '#db61a2',

  '--radius-xs': '4px',
  '--radius-sm': '8px',
  '--radius-md': '12px',
  '--radius-lg': '16px',
  '--radius-xl': '16px',
  '--radius-full': '9999px',
  '--shadow-sm': 'none',
  '--shadow-md': 'none',
  '--shadow-lg': 'none'
};
