import { ThemePreset } from '../types';
import { DEFAULT_LIGHT_TOKENS, DEFAULT_DARK_TOKENS } from './defaultTokens';

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'perplexta_warm',
    nameEn: 'Perplexta Editorial Warm (Default)',
    nameAr: 'بيربليكستا الدافئ (الافتراضي)',
    descriptionEn: 'Warm editorial cream canvas with terracotta accent and deep ink typography',
    descriptionAr: 'لوحة تحريرية دافئة بلون كريمي مع لمسات تيراكوتا ترابية وخطوط حبرية نقية',
    author: 'Perplexta Core Team',
    version: '2.0.0',
    previewColors: {
      surface: '#faf9f5',
      card: '#efe9de',
      accent: '#cc785c',
      text: '#141413',
    },
    tokens: {
      light: { ...DEFAULT_LIGHT_TOKENS },
      dark: { ...DEFAULT_DARK_TOKENS },
    },
  },
  {
    id: 'midnight_obsidian',
    nameEn: 'Midnight Obsidian OLED',
    nameAr: 'أوبسيديان منتصف الليل (OLED أسود نقي)',
    descriptionEn: 'Pure black background optimized for OLED displays with vibrant amber highlights',
    descriptionAr: 'خلفية سوداء نقية موفرة ومخصصة لشاشات OLED مع لمسات كهرمانية نارية ساطعة',
    author: 'Perplexta Design Lab',
    version: '2.0.0',
    previewColors: {
      surface: '#000000',
      card: '#0d0d0d',
      accent: '#f59e0b',
      text: '#ffffff',
    },
    tokens: {
      light: {
        ...DEFAULT_LIGHT_TOKENS,
        '--surface-page': '#f8fafc',
        '--surface-canvas': '#f8fafc',
        '--surface-card': '#ffffff',
        '--surface-subtle': '#f1f5f9',
        '--surface-inset': '#e2e8f0',
        '--fg-primary': '#0f172a',
        '--accent': '#d97706',
        '--accent-hover': '#b45309',
        '--bg-accent-emphasis': '#d97706',
        '--border-accent': '#d97706',
      },
      dark: {
        ...DEFAULT_DARK_TOKENS,
        '--surface-page': '#000000',
        '--surface-canvas': '#000000',
        '--surface-card': '#0d0d0d',
        '--surface-raised': '#141414',
        '--surface-subtle': '#181818',
        '--surface-inset': '#1f1f1f',
        '--bg-input': '#141414',
        '--fg-primary': '#ffffff',
        '--fg-secondary': '#a3a3a3',
        '--accent': '#f59e0b',
        '--accent-hover': '#fbbf24',
        '--fg-accent': '#fbbf24',
        '--bg-accent-emphasis': '#f59e0b',
        '--border-default': 'rgba(255, 255, 255, 0.08)',
        '--border-outer-input': 'rgba(255, 255, 255, 0.12)',
        '--border-accent': '#f59e0b',
        '--chat-bubble-user': '#f59e0b',
        '--admin-nav-bg': '#0a0a0a',
        '--admin-table-header-bg': '#121212',
      },
    },
  },
  {
    id: 'emerald_citadel',
    nameEn: 'Emerald Citadel',
    nameAr: 'قلعة الزمرد (Botanical Green)',
    descriptionEn: 'Deep botanical forest tones with luminous emerald and jade accents',
    descriptionAr: 'درجات الغابة العميقة مع إضاءات زمردية ويشمية راقية وفائقة الفخامة',
    author: 'Perplexta Design Lab',
    version: '2.0.0',
    previewColors: {
      surface: '#091512',
      card: '#0f201b',
      accent: '#10b981',
      text: '#ecfdf5',
    },
    tokens: {
      light: {
        ...DEFAULT_LIGHT_TOKENS,
        '--surface-page': '#f0fdf4',
        '--surface-canvas': '#f0fdf4',
        '--surface-card': '#e6f8ee',
        '--surface-subtle': '#dcfce7',
        '--surface-inset': '#bbf7d0',
        '--fg-primary': '#064e3b',
        '--accent': '#059669',
        '--accent-hover': '#047857',
        '--bg-accent-emphasis': '#059669',
        '--border-accent': '#059669',
      },
      dark: {
        ...DEFAULT_DARK_TOKENS,
        '--surface-page': '#091512',
        '--surface-canvas': '#091512',
        '--surface-card': '#0f201b',
        '--surface-raised': '#142923',
        '--surface-subtle': '#18322b',
        '--surface-inset': '#1d3d34',
        '--bg-input': '#142923',
        '--fg-primary': '#ecfdf5',
        '--fg-secondary': '#a7f3d0',
        '--accent': '#10b981',
        '--accent-hover': '#34d399',
        '--fg-accent': '#34d399',
        '--bg-accent-emphasis': '#059669',
        '--border-default': 'rgba(167, 243, 208, 0.12)',
        '--border-accent': '#10b981',
        '--chat-bubble-user': '#059669',
        '--admin-nav-bg': '#0c1a16',
        '--admin-table-header-bg': '#142923',
      },
    },
  },
  {
    id: 'nordic_azure',
    nameEn: 'Nordic Azure & Indigo',
    nameAr: 'الأزرق القطبي والأنديجو (Nordic Azure)',
    descriptionEn: 'Cold high-tech aesthetic with deep navy substrates and cobalt blue highlights',
    descriptionAr: 'تصميم تقني عالي البرودة مع خلفيات كحلية عميقة ولمسات زرقاء سماوية حيوية',
    author: 'Perplexta Engineering',
    version: '2.0.0',
    previewColors: {
      surface: '#0b1120',
      card: '#131b2e',
      accent: '#3b82f6',
      text: '#f8fafc',
    },
    tokens: {
      light: {
        ...DEFAULT_LIGHT_TOKENS,
        '--surface-page': '#f8fafc',
        '--surface-canvas': '#f8fafc',
        '--surface-card': '#ffffff',
        '--surface-subtle': '#f1f5f9',
        '--surface-inset': '#e2e8f0',
        '--fg-primary': '#0f172a',
        '--accent': '#2563eb',
        '--accent-hover': '#1d4ed8',
        '--bg-accent-emphasis': '#2563eb',
        '--border-accent': '#2563eb',
      },
      dark: {
        ...DEFAULT_DARK_TOKENS,
        '--surface-page': '#0b1120',
        '--surface-canvas': '#0b1120',
        '--surface-card': '#131b2e',
        '--surface-raised': '#1a243d',
        '--surface-subtle': '#1e2942',
        '--surface-inset': '#24324f',
        '--bg-input': '#1a243d',
        '--fg-primary': '#f8fafc',
        '--fg-secondary': '#94a3b8',
        '--accent': '#3b82f6',
        '--accent-hover': '#60a5fa',
        '--fg-accent': '#60a5fa',
        '--bg-accent-emphasis': '#2563eb',
        '--border-default': 'rgba(148, 163, 184, 0.12)',
        '--border-accent': '#3b82f6',
        '--chat-bubble-user': '#2563eb',
        '--admin-nav-bg': '#0e1629',
        '--admin-table-header-bg': '#17223b',
      },
    },
  },
  {
    id: 'royal_crimson',
    nameEn: 'Imperial Crimson Ember',
    nameAr: 'الجمر القرمزي الإمبراطوري (Royal Crimson)',
    descriptionEn: 'Prestige dark palette with smoky carbon foundations and crimson rubies',
    descriptionAr: 'لوحة داكنة فاخرة مع أرضيات كربونية ولمسات ياقوتية ملكية قانية',
    author: 'Perplexta Luxury Division',
    version: '2.0.0',
    previewColors: {
      surface: '#151112',
      card: '#1f181a',
      accent: '#e11d48',
      text: '#fff1f2',
    },
    tokens: {
      light: {
        ...DEFAULT_LIGHT_TOKENS,
        '--surface-page': '#fff1f2',
        '--surface-canvas': '#fff1f2',
        '--surface-card': '#ffe4e6',
        '--surface-subtle': '#fecdd3',
        '--surface-inset': '#fda4af',
        '--fg-primary': '#881337',
        '--accent': '#e11d48',
        '--accent-hover': '#be123c',
        '--bg-accent-emphasis': '#e11d48',
        '--border-accent': '#e11d48',
      },
      dark: {
        ...DEFAULT_DARK_TOKENS,
        '--surface-page': '#151112',
        '--surface-canvas': '#151112',
        '--surface-card': '#1f181a',
        '--surface-raised': '#2a1f23',
        '--surface-subtle': '#34262b',
        '--surface-inset': '#3f2e34',
        '--bg-input': '#2a1f23',
        '--fg-primary': '#fff1f2',
        '--fg-secondary': '#fda4af',
        '--accent': '#f43f5e',
        '--accent-hover': '#fb7185',
        '--fg-accent': '#fb7185',
        '--bg-accent-emphasis': '#e11d48',
        '--border-default': 'rgba(253, 164, 175, 0.12)',
        '--border-accent': '#f43f5e',
        '--chat-bubble-user': '#e11d48',
        '--admin-nav-bg': '#191415',
        '--admin-table-header-bg': '#261b1f',
      },
    },
  },
];
