import express from 'express';
import { authenticateToken } from '../middleware/auth.js';
import { VideoResourceProvider } from '../services/videoResourceProvider.js';

const router = express.Router();

/**
 * GET /api/video-resources/chat/:chatId
 * Retrieve the high-definition video resources associated with a specific chat session.
 */
router.get('/chat/:chatId', authenticateToken, async (req: any, res) => {
  try {
    const chatId = parseInt(req.params.chatId);
    if (isNaN(chatId)) {
      return res.status(400).json({ error: 'Invalid or missing chatId parameter.' });
    }

    const resources = await VideoResourceProvider.getResourcesByChat(chatId);
    res.json(resources);
  } catch (err: any) {
    res.status(500).json({ error: err.message || 'Failed to retrieve video resources for chat.' });
  }
});

/**
 * GET /api/video-resources/user
 * Retrieve all video resources generated by/for the currently authenticated user.
 */
router.get('/user', authenticateToken, async (req: any, res) => {
  try {
    const userId = String(req.user.id);
    const resources = await VideoResourceProvider.getResourcesByUser(userId);
    res.json(resources);
  } catch (err: any) {
    res.status(500).json({ error: err.message || 'Failed to retrieve video resources for user.' });
  }
});

/**
 * GET /api/video-resources/message/:messageId
 * Retrieve the specific video resource for a single chat message ID.
 */
router.get('/message/:messageId', authenticateToken, async (req: any, res) => {
  try {
    const messageId = parseInt(req.params.messageId);
    if (isNaN(messageId)) {
      return res.status(400).json({ error: 'Invalid or missing messageId parameter.' });
    }

    const resource = await VideoResourceProvider.getResourceByMessage(messageId);
    if (!resource) {
      return res.status(404).json({ error: 'No video resource found associated with this message ID.' });
    }

    res.json(resource);
  } catch (err: any) {
    res.status(500).json({ error: err.message || 'Failed to retrieve video resource for message.' });
  }
});

export default router;
