export const ALL_TOOLS = [
  "chat",
  "chat_fast",
  "chat_pro",
  "chat_reasoning",
  "perplexta_analysis",
  "legal_analysis",
  "notebook",
  "image",
  "video",
  "stt",
  "tts",
  "learning",
  "code",
  "canvas",
  "sovereign_memory",
  "sovereign_search",
  "x402_api",
  "storage_mb",
  "marketplace_listings",
] as const;
