import { User, Language, Theme } from './user.types';
import { SiteSettings, MemoryNotification, MemoryNotificationType } from './ui.types';
import { Socket } from 'socket.io-client';

export interface AppContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  theme: Theme;
  setTheme: (theme: Theme) => void;
  user: User | null;
  setUser: (user: User | null) => void;
  token: string | null;
  setToken: (token: string | null) => void;
  isAuthReady: boolean;
  setIsAuthReady: (ready: boolean) => void;
  balance: number;
  setBalance: (balance: number) => void;
  balanceUSD: number;
  setBalanceUSD: (balance: number) => void;
  socket: Socket | null;
  logout: () => void;
  dir: 'rtl' | 'ltr';
  t: (key: string, params?: Record<string, any>) => string;
  showAuthModal: boolean;
  setShowAuthModal: (show: boolean) => void;
  authView: 'login' | 'signup' | 'forgot-password';
  setAuthView: (view: 'login' | 'signup' | 'forgot-password') => void;
  rememberMe: boolean;
  setRememberMe: (val: boolean) => void;
  showNotification: (msg: string, type?: 'success' | 'error' | 'info' | 'warning') => void;
  siteSettings: SiteSettings;
  setSiteSettings: (settings: SiteSettings) => void;
  isSubscribed: boolean;
  activePlan: any;
  economySettings: any;
  setEconomySettings: (settings: any) => void;
  isMobile: boolean;
  deferredPrompt: any;
  isInstallable: boolean;
  isInstalling: boolean;
  installApp: () => void;
  isSidebarOpen: boolean;
  setIsSidebarOpen: (open: boolean) => void;
  notifications: any[];
  setNotifications: (notifs: any[]) => void;
  plans: any[];
  setPlans: (plans: any[]) => void;
  isEconomyLoading: boolean;
  isPlansLoading: boolean;
  isSettingsLoading: boolean;
  refreshEconomy: () => Promise<void>;
  memoryNotification: MemoryNotification;
  setMemoryNotification: (notif: MemoryNotification) => void;
  setIsAuthModalOpen: (show: boolean) => void;
  isAuthModalOpen: boolean;
  loginWithGoogle: () => Promise<void>;
  login: (email: string, password: string) => Promise<{ success: boolean; error?: string }>;
  signup: (email: string, password: string, name: string, ref?: string) => Promise<{ success: boolean; error?: string }>;
  unreadCount: number;
  markAsRead: (id: number) => Promise<void>;
  markAllAsRead: () => Promise<void>;
  deleteNotification: (id: number) => Promise<void>;
  clearAllNotifications: () => Promise<void>;
  closeMemoryNotification: () => void;
  triggerMemoryNotification: (type: MemoryNotificationType, desc?: string) => void;
  milestoneData: any;
  setMilestoneData: (data: any) => void;
  setIsOperationPending: (pending: boolean) => void;
  isOperationPending: boolean;
  refreshUser: () => Promise<void>;
  payWithBalance: (planId: string, billingCycle: 'monthly' | 'annual') => Promise<{ success: boolean; message?: string; error?: string }>;
  stripeCheckout: (planId: string, billingCycle: 'monthly' | 'annual') => Promise<{ url?: string; error?: string }>;
}
