import { MemoryNotification } from '../components/MemoryNotification';
import React, { useState, useRef, useEffect, useLayoutEffect, useMemo } from 'react';
import { useVideoPlayback } from '../hooks/useVideoPlayback';
import { createPortal } from 'react-dom';
import { useParams, useNavigate } from 'react-router-dom';
import Prism from 'prismjs';
import 'prismjs/themes/prism-tomorrow.css';
import 'prismjs/components/prism-javascript';
import 'prismjs/components/prism-typescript';
import 'prismjs/components/prism-css';
import 'prismjs/components/prism-json';
import 'prismjs/components/prism-python';
import 'prismjs/components/prism-bash';
import 'prismjs/components/prism-jsx';
import 'prismjs/components/prism-tsx';
import 'prismjs/components/prism-markup';