import { pool } from '../db/index.js';
import { saveFileMetadata } from './files.js';

export interface VideoResource {
  id?: number;
  user_id: number;
  chat_id: number | null;
  message_id: number | null;
  file_url: string;
  prompt: string | null;
  provider: string | null;
  model: string | null;
  duration: number | null;
  aspect_ratio: string | null;
  resolution: string | null;
  metadata: any;
  created_at?: Date;
}

export class VideoResourceProvider {
  /**
   * Store a brand-new generated video clip with full metadata and message/chat associations.
   */
  static async storeVideoResource(
    userId: string,
    chatId: number | null,
    messageId: number | null,
    fileUrl: string,
    prompt: string,
    provider: string,
    model: string,
    duration: number,
    aspectRatio: string,
    resolution: string,
    metadata: any = {}
  ): Promise<VideoResource> {
    if (!pool) throw new Error('Database initializing');

    console.log(`[VideoResourceProvider] Storing video resource: url=${fileUrl}, userId=${userId}, chatId=${chatId}, messageId=${messageId}`);

    // Parse numeric user ID
    const uId = parseInt(userId);
    if (isNaN(uId)) {
      throw new Error(`Invalid non-numeric user_id: ${userId}`);
    }

    // 1. Insert into the standardized video_resources table
    const query = `
      INSERT INTO video_resources (
        user_id, chat_id, message_id, file_url, prompt, provider, model, duration, aspect_ratio, resolution, metadata
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
      RETURNING *
    `;

    const values = [
      uId,
      chatId || null,
      messageId || null,
      fileUrl,
      prompt || '',
      provider || '',
      model || '',
      duration || 5,
      aspectRatio || '16:9',
      resolution || '1080p',
      JSON.stringify(metadata)
    ];

    const result = await pool.query(query, values);
    const storedResource = result.rows[0];

    // 2. Register under user_files as well for global document library compatibility
    try {
      const filename = fileUrl.startsWith('/uploads/') ? fileUrl.replace('/uploads/', '') : fileUrl;
      await saveFileMetadata(userId, {
        file_name: `AI_Video_${Date.now()}.mp4`,
        file_url: filename,
        file_size: 1024 * 1024 * (duration || 5), // Estimate size for display/listing if not computed
        mime_type: 'video/mp4',
        file_type: 'video',
        metadata: {
          generated: true,
          videoResourceId: storedResource.id,
          prompt,
          provider,
          model,
          chat_id: chatId
        }
      });
    } catch (err: any) {
      console.warn('[VideoResourceProvider] Failed to register video under user_files, ignoring.', err.message);
    }

    return storedResource;
  }

  /**
   * Retrieve all video resources associated with a specific chat session.
   */
  static async getResourcesByChat(chatId: number): Promise<VideoResource[]> {
    if (!pool) throw new Error('Database initializing');
    const result = await pool.query(
      'SELECT * FROM video_resources WHERE chat_id = $1 ORDER BY created_at DESC',
      [chatId]
    );
    return result.rows;
  }

  /**
   * Retrieve all video resources generated by/for a specific user.
   */
  static async getResourcesByUser(userId: string): Promise<VideoResource[]> {
    if (!pool) throw new Error('Database initializing');
    const uId = parseInt(userId);
    if (isNaN(uId)) return [];

    const result = await pool.query(
      'SELECT * FROM video_resources WHERE user_id = $1 ORDER BY created_at DESC',
      [uId]
    );
    return result.rows;
  }

  /**
   * Retrieve the video resource associated directly with a single chat message.
   */
  static async getResourceByMessage(messageId: number): Promise<VideoResource | null> {
    if (!pool) throw new Error('Database initializing');
    const result = await pool.query(
      'SELECT * FROM video_resources WHERE message_id = $1 LIMIT 1',
      [messageId]
    );
    return result.rows[0] || null;
  }

  /**
   * Relink or update an existing video resource's association to a chat message.
   */
  static async associateMessageWithVideo(messageId: number, videoUrl: string): Promise<boolean> {
    if (!pool) throw new Error('Database initializing');

    // Clean exact file url from full URL tags if formatted as a markdown tag
    let cleanedUrl = videoUrl;
    if (videoUrl.includes('](')) {
      const match = videoUrl.match(/\]\((.*?)\)/);
      if (match && match[1]) {
        cleanedUrl = match[1];
      }
    }
    // strip out aspect ratios or hash indicators
    cleanedUrl = cleanedUrl.split('#')[0];

    const result = await pool.query(
      'UPDATE video_resources SET message_id = $1 WHERE file_url = $2 OR file_url LIKE $3 RETURNING id',
      [messageId, cleanedUrl, `%${cleanedUrl.replace('/uploads/', '')}`]
    );

    return result.rowCount > 0;
  }
}
