/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, NetworkOnly } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by build process
precacheAndRoute(self.__WB_MANIFEST);

cleanupOutdatedCaches();

// Background Sync for API calls (messages, reports, etc.)
const bgSyncPlugin = new BackgroundSyncPlugin('perplexta-sync-queue', {
  maxRetentionTime: 24 * 60, // Retry for max 24 hours
});

// Route for background sync - specifically for messages and reports that might fail offline
registerRoute(
  ({ url }) => url.pathname.includes('/api/chats') || 
               url.pathname.includes('/api/messages') ||
               url.pathname.includes('/api/reports'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'POST'
);

registerRoute(
  ({ url }) => url.pathname.includes('/api/chats') || 
               url.pathname.includes('/api/messages'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'PATCH'
);

// Runtime caching
registerRoute(
  ({ request }) => request.destination === 'document',
  new NetworkFirst({
    cacheName: 'html-pages',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 86400,
      }),
    ],
  })
);

registerRoute(
  ({ url }) => url.hostname.includes('googleusercontent.com') || 
               url.hostname.includes('unsplash.com') || 
               url.hostname.includes('githubusercontent.com') || 
               url.pathname.includes('/uploads/') || 
               url.pathname.includes('/avatar'),
  new NetworkFirst({
    cacheName: 'external-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 86400,
      }),
    ],
  })
);

registerRoute(
  ({ request, url }) =>
    (['script', 'style', 'font', 'image'].includes(request.destination) ||
     /\.(?:js|css|png|jpg|jpeg|svg|gif|webp|woff|woff2|ttf|eot|ico)$/i.test(url.pathname)) && 
    url.origin === self.location.origin,
  new CacheFirst({
    cacheName: 'static-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }),
    ],
  })
);

// Listen for messages from the client
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
  
  // Custom message to check sync queue status
  if (event.data && event.data.type === 'GET_SYNC_STATUS') {
    getSyncQueueStatus().then(status => {
      event.ports[0].postMessage(status);
    });
  }
});

async function getSyncQueueStatus() {
  try {
    // Workbox Background Sync uses IndexedDB to store requests
    // The database name is usually 'workbox-background-sync'
    // and the store name matches the queue name.
    const dbName = 'workbox-background-sync';
    const storeName = 'requests'; // This might vary depending on Workbox version, but usually it's 'requests'
    
    return new Promise((resolve) => {
      const request = indexedDB.open(dbName);
      request.onerror = () => resolve({ count: 0 });
      request.onsuccess = (event: any) => {
        const db = event.target.result;
        try {
          if (!db.objectStoreNames.contains(storeName)) {
             resolve({ count: 0 });
             return;
          }
          const transaction = db.transaction(storeName, 'readonly');
          const store = transaction.objectStore(storeName);
          const countRequest = store.count();
          countRequest.onsuccess = () => {
            resolve({ count: countRequest.result });
          };
          countRequest.onerror = () => resolve({ count: 0 });
        } catch (e) {
          resolve({ count: 0 });
        }
      };
    });
  } catch (e) {
    return { count: 0 };
  }
}
